http:
  host: 127.0.0.1
  port: 22800
  read_timeout: 15s
  write_timeout: 15s
  shutdown_timeout: 10s

maiyatian:
  cookie: 'your-maiyatian-cookie'
  user_agent: 'your-user-agent'
  timeout: 15s

upload:
  base_url: http://127.0.0.1:8850
  api_key: your-backend-apikey
  timeout: 15s
